### ISSUE TITLE
innaugural meeting

### ISSUE THREAD

**Issue by MylesBorins** [dimsumjs/sf#1]
Where?

When?

OMNOMNOMNOM

**Comment by sfrisk** [comment]
MAINE!

Oh wait, nope it's for SF. Wish I could go though!

**Comment by visnup** [comment]
SF!

**Comment by MylesBorins** [comment]
I'll add you to the organization and make a repo

**Comment by visnup** [comment]
for price, location, and ease of getting a table, I like [City View](http://cityviewdimsum.com) in Chinatown.

**Comment by MylesBorins** [comment]
I'm eating at great eastern right now.

Yum!

**Comment by MylesBorins** [comment]
How do people feel about July 18th or 19th?

**Comment by jedireza** [comment]
:grin: :+1:

**Comment by visnup** [comment]
I won't be in town. :disappointed: could do 11th or 12th. otherwise, don't wait for me if others can go.

**Comment by MylesBorins** [comment]
I'm out 11th and 12th

We could do it the 26th (25th is node bots day)

**Comment by jedireza** [comment]
The 25th is also NodeSchoolSF :tada: I can do the 26th though.

**Comment by visnup** [comment]
I travel too much (all of my weekends in July are booked except for 11-12). what do you think about weekday lunch?

**Comment by MylesBorins** [comment]
I would like to propose August 2nd at Great Eastern.

Thoughts?

**Comment by jedireza** [comment]
:airplane: I'm getting back from LA on the 2nd. But I'll take a rain check. :umbrella:

**Comment by visnup** [comment]
I can/will be there.

**Comment by visnup** [comment]
🍤

**Comment by MylesBorins** [comment]
Was great success!
