### ISSUE TITLE
hot pot

### ISSUE THREAD

**Issue by visnup** [dimsumjs/sf#2]
related, hot pot from [Little Sheep](http://www.littlesheephotpot.com) (also in Chinatown) is probably a good idea too.

**Comment by MylesBorins** [comment]
mmmmmm. hotpot.js could be delicious.

I have also been discussing a potential korean-bbq.js

**Comment by visnup** [comment]
korean bbq fu isn't strong enough in SF. would have to go down to LA or
over to NYC.

**Comment by MylesBorins** [comment]
Have you been to yakiniq yet?

**Comment by visnup** [comment]
I have not. I will go try it. Though, that's an odd name: yakiniku is Japanese grilled meat.

**Comment by MylesBorins** [comment]
Interesting... I definitely get bimbambop

**Comment by visnup** [comment]
yeah, yelp says Korean. and it looks Korean. but the name is not Korean. 😕

**Comment by MylesBorins** [comment]
Did this happen?
