### ISSUE TITLE
NUMBA TWO

### ISSUE THREAD

**Issue by MylesBorins** [dimsumjs/sf#3]
So I'm thinking either August 23rd or September 13th

Specifically imagining we could do this at [Hong Kong Lounge](https://foursquare.com/v/hong-kong-lounge-%E7%A9%97%E9%A6%99%E9%85%92%E5%AE%B6/4b19d3f4f964a520f6e423e3)

**Comment by benvinegar** [comment]
13th and I'm there.

**Comment by cdelauder** [comment]
September 13th and I'm in!

**Comment by cdelauder** [comment]
Are we doing this?

**Comment by MylesBorins** [comment]
LETS DO IT!

I almost forgot... memory a bit "dusty" :P

**Comment by cdelauder** [comment]
LOL! what time? I want to do this: https://www.facebook.com/events/668189289983041/
so hopefully they can be non-blocking.

**Comment by MylesBorins** [comment]
Would you prefer 11:30am or 1pm? I was aiming for 1... but we could go earlier

**Comment by MylesBorins** [comment]
I'm going to call it for 11:30 to be safe

**Comment by MylesBorins** [comment]
I wonder if anyone will see this in time :D

**Comment by cdelauder** [comment]
11:30 works for me. Guess Twitter is our only hope.

**Comment by MylesBorins** [comment]
Tickets --> https://ti.to/dimsum-js/volume-2

**Comment by MylesBorins** [comment]
Tweet --> https://twitter.com/thealphanerd/status/642899136770015232

(sorry for email spam people in thread)

**Comment by MylesBorins** [comment]
That was delicious!
