### ISSUE TITLE
Dimsum #3

### ISSUE THREAD

**Issue by cdelauder** [dimsumjs/sf#5]
We're overdue for the sequel. Who's with me?

Otherwise I just end up with delivery and it looks like this:
![eating](https://cloud.githubusercontent.com/assets/6435031/11619703/de9e7ba6-9c5f-11e5-8dd9-b7d65515a90d.gif)

**Comment by MylesBorins** [comment]
I think the only day that works for me this month is the 21st. thoughts?

**Comment by jedireza** [comment]
Woohoo, the 21st is a Monday and I'll be back in town. I'm down.

**Comment by MylesBorins** [comment]
Oops I meant 20th.but we can so the 21st tol

**Comment by jakl** [comment]
Delivery is rarely as good, I might be around depending on weather, and deliciousness.

**Comment by cdelauder** [comment]
The 20th is ideal for me. But I could make the 21st work if that is the consensus.

**Comment by jakl** [comment]
(assuming) 21st is jedireza's first day back. LGTM

**Comment by jedireza** [comment]
If the weekend is better for everyone go for it. I'll make it one day :wink:

**Comment by cdelauder** [comment]
Sounds like everyone can actually make the 21st, so let's go then. Now our task it to go forth and spread the word!

**Comment by cdelauder** [comment]
Any suggestions for where?

**Comment by MylesBorins** [comment]
Tickets are up... where are we going?

**Comment by MylesBorins** [comment]
https://ti.to/dimsum-js/dec-21st-edition

**Comment by nebrius** [comment]
I can do the 21st!

**Comment by mikolalysenko** [comment]
Yes!

**Comment by nebrius** [comment]
Dim sum tomorrow! Any ideas where we want to go?

**Comment by MylesBorins** [comment]
I'm assuming many folks are working in Soma.

Yank sing or city view?

They are both a little pricier than our normal choices. I'm totally up for going to china town though.

**Comment by jakl** [comment]
So last minute holiday plans, I'll be going out of town for a vacation tonight...but I'd love to have some dimsum and talk JS. Maybe I'll just stop for dimsum along the way and talk JS in a chatroom or something ¯_(ツ)_/¯

**Comment by nebrius** [comment]
I'm up for whatever. I'll probably be getting to the city in time for lunch, so proximity to the office isn't an issue for me. I'm also not particularly familiar with the SF dim sum scene :)

**Comment by cdelauder** [comment]
I don't know enough about dimsum to successfully choose a place.

**Comment by MylesBorins** [comment]
Are people open to going to china town? If so we should go to great eastern.

**Comment by cdelauder** [comment]
I'm fine with it.

**Comment by MylesBorins** [comment]
Cool. 

http://www.yelp.com/biz/great-eastern-restaurant-san-francisco

I'll be there for 12:30

There are 6 people registered.

**Comment by mikolalysenko** [comment]
:+1:

**Comment by jedireza** [comment]
Got in really late last night and have been offline for the last week. :flushed:

I see Tito registration is closed, but I'd still like to join.

**Comment by MylesBorins** [comment]
You can totes come! Try tickets again :p

**Comment by jedireza** [comment]
Thanks! See you all this afternoon. :shipit:

**Comment by MylesBorins** [comment]
So this happened
