### ISSUE TITLE
DIMSUM IV: The Next Generation -- 1/13/16

### ISSUE THREAD

**Issue by ike** [dimsumjs/sf#6]
Dim sum! This Wednesday, Jan 13th, at 1pm. 

![that. right. there.](http://i.giphy.com/14iIhHvOIp0s6c.gif)

I am not the expert on the best dim sum in SF, so I'll defer to you all on the place.

**Comment by MylesBorins** [comment]
@visnup had some strong opinions last time.

**Comment by jedireza** [comment]
:pager:

**Comment by MylesBorins** [comment]
So we are thinking about going to Hong Kong Lounge in the sunset

http://hongkongloungesf.com/

1pm?

**Comment by jedireza** [comment]
Aw-shucks, that place looks good. I thought I'd be able to swing it today, but I can't. Is the bubble popping? :stuck_out_tongue_winking_eye:

**Comment by MylesBorins** [comment]
OMG SUCH FUN

**Comment by mikolalysenko** [comment]
Ah, I just realized I missed this.  Need to watch this repo.
