### ISSUE TITLE
January / February Edition

### ISSUE THREAD

**Issue by MylesBorins** [dimsumjs/sf#8]
OMG I'm coming through town

Who want to go for DIMSUM?

Proposed dates:

Saturday, Jan. 27 😄
Sunday, Jan. 28 🎉
Saturday, Feb 3 ❤️

(vote with reactions)

**Comment by MylesBorins** [comment]
OK... let's do This Sunday the 28th, and Next Sunday Feb 3rd

DOUBLE DIM SUM

Any objections to Hong Kong Lounge 2?

**Comment by MylesBorins** [comment]
Noon Sunday, be there 🤣

**Comment by Trott** [comment]
> OK... let's do This Sunday the 28th, and Next Sunday Feb 3rd

You mean Saturday the 3rd, right?

**Comment by MylesBorins** [comment]
Yes indeed

**Comment by MylesBorins** [comment]
Tomorrow, 12, Hong Kong lounge (original)

**Comment by Trott** [comment]
I'm 50/50 on being able to show up tomorrow. Totally OK if I just show up or don't?

**Comment by MylesBorins** [comment]
Absolutely!

**Comment by MylesBorins** [comment]
To super confirm

Today, at noon (one hour from now), at Hong Kong Lounge
Heres a link to the location --> https://goo.gl/maps/1hZDLuK8WeB2
